version: "3.8"

services:

  db:
    image: mysql
    container_name: mysqldb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=bootcamp
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password

  minio:
    image: minio/minio
    container_name: minio
    restart: always
    volumes:
    - ./datalake:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
